[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "goldfish"
version = "0.9.6"
requires-python = "==3.13.*"
dependencies = ["tomli-w", "PyYAML", "typer", "chonkie"]

[project.urls]
Homepage = "https://github.com/miztertea/goldfish"
Repository = "https://github.com/miztertea/goldfish"

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
goldfish = "goldfish.cli:app"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.hatch.build.targets.wheel]
packages = ["src/goldfish"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
